pill_my_heart/views/address_views.py
from flask import Blueprint, render_template, url_for
from pill_my_heart.models import Question
from werkzeug.utils import redirect
import folium

bp = Blueprint('address', __name__, url_prefix='/')


@bp.route('/address/', methods=('GET', 'POST'))
def index():

    return render_template('address/address.html', latitude=37.5285568, longitude=126.8885657 )

pill_my_heart/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from datetime import datetime
import sqlite3
from pill_my_heart import db
from pill_my_heart.forms import UserCreateForm, UserLoginForm
from pill_my_heart.models import User, Medical_History, Medicine_History

bp = Blueprint('auth', __name__, url_prefix='/auth')

conn=sqlite3.connect("pybo.db",check_same_thread=False)
cur=conn.cursor()

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data,
                        birth_year=form.birth_year.data,
                        gender=form.gender.data,
                        re_dt=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                        )
            db.session.add(user)
            db.session.commit()

            medical_history = Medical_History(age=form.birth_year.data,
                                                gender=form.gender.data,
                                                re_dt=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                                                medical_nm=form.medical_nm.data)
            medicine_history = Medicine_History(age=form.birth_year.data,
                                                gender=form.gender.data,
                                                re_dt=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                                                medicine_nm=form.medicine_nm.data)
            db.session.add(medical_history)
            db.session.add(medicine_history)
            db.session.commit()

            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.username
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/address.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(username=user_id).first()
        # g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

pill_my_heart/views/main_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/', methods=('GET', 'POST'))
def index():

    return render_template('main.html')

pill_my_heart/views/pill_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect,secure_filename
from datetime import datetime
import os
from pill_my_heart import db
from pill_my_heart.forms import UserCreateForm, UserLoginForm
from pill_my_heart.models import User

bp = Blueprint('pill_search', __name__, url_prefix='/')


@bp.route('/pill_search')
def pill_search():
    return render_template('pill/pill_search.html' )

@bp.route('/uploadimg', methods=["POST"])
def imguploading():

    uploaded_file1 = request.files['file1']
    uploaded_file2 = request.files['file2']


    print(uploaded_file1)
    uploaded_file1.save(
        os.path.join(r'C:\testproject\pill_my_heart\uploadimg\\'+secure_filename(uploaded_file1.filename)))
    uploaded_file2.save(
        os.path.join(r'C:\testproject\pill_my_heart\uploadimg\\' + secure_filename(uploaded_file2.filename)))

    return render_template('pill/pill_search.html' )

@bp.route('/pill_result/', methods=('GET', 'POST'))
def result():
    return render_template('pill/pill_result.html')

@bp.route('/pill_warning/', methods=('GET', 'POST'))
def warning():
    return  render_template('pill/pill_warning.html')

pill_my_heart/views/question_views.py
from flask import Blueprint, render_template, request, url_for
from werkzeug.utils import redirect
from datetime import datetime
from pill_my_heart import db
from pill_my_heart.models import Question
from pill_my_heart.forms import QuestionForm

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    question_list = Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/create/', methods=(['GET', 'POST']))
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/question_form.html', form=form)

pill_my_heart/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet">
    <!-- pill_my_heart CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
     <link rel="icon" type="image/x-icon" href="./favicon.png">
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <py-env>
      - folium
      - pandas
    </py-env>

    <title>pill my heart!</title>
</head>
<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <header class="p-3 bg-dark text-white">
    <div class="container-fluid">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a class="navbar-brand text-white" href="{{ url_for('main.index') }}">PMH</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                {% if g.user %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ url_for('address.index') }}">근처 약국 찾기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ url_for('pill_search.pill_search') }}">약 정보 검색</a>
                    </li>
                </ul>
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <div class="text-end">
                        <form class="w-100 me-3">
                            <input class="fomr-control me-2" type="search" placeholder="검색" aria-label="Search">
                            <button class="btn btn-outline-warning" type="submit">
                            <span class="blind">검색</span>
                            <span class="ico_search_submit"></span>
                        </button>
                        </form>
                    </div>
                </form>
                </ul>
                {% else %}
                   <ul class="navbar-nav m1-auto mb-2 mb-lg-0">
                       <li class="nav-item">
                           <a class="nav-link text-white px-2 text-secondary" href="{{ url_for('auth.signup') }}">회원가입</a>
                       </li>
                       <li class="nav-item">
                           <a class="nav-link text-white px-2 text-secondary" href="{{ url_for('auth.login') }}">로그인</a>
                       </li>
                       <li class="nav-item">
                           <a class="nav-link text-white" href="{{ url_for('address.index') }}">근처 약국 찾기</a>
                       <li class="nav-item">
                           <a class="nav-link text-white" href="{{ url_for('pill_search.pill_search') }}">약 정보 검색</a>
                       </li>
                   </ul>
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <form class="w-100 me-3">
                        <input class="form-control-lg me-2" type="search" placeholder="검색" aria-label="Search">
                        <button class="btn btn-outline-warning" type="submit" onclick="window.location.href='/pill_result'">
                            <span class="blind">검색</span>
                            <span class="ico_search_submit"></span>
                        </button>
                    </form>
                </form>
            </div>
                {% endif %}
            </div>
        </header>
    </div>
</nav>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>
<script>
/**
  window.onload = function() {
  var startPos;
  var geoSuccess = function(position) {
    startPos = position;
    document.getElementById('startLat').innerHTML = startPos.coords.latitude;
    document.getElementById('startLon').innerHTML = startPos.coords.longitude;
  };
  navigator.geolocation.getCurrentPosition(geoSuccess);
  console.log(geoSuccess);
};
*/

</script>

pill_my_heart/templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pill_my_heart/templates/main.html
{% extends 'base.html' %}
{% block content %}
<html lang="ko">
    <main>
        <div class="row g-6" data-path="0.0.1">
            <div class="col-12 col-md-6 col-lg-3" data-path="0.0.1.0">
                <a href="#" data-path="0.0.1.0.0">
                    <div class="position-relative mw-100" data-path="0.0.1.0.0.0">
                        <img class="w-100 rounded-3" src="/static/woman.jpg" alt data-config-id="auto-img-1-1" data-path="0.0.1.0.0.0.0">
                        <div class="position-absolute bottom-0 start-0 w-100 rounded-3" data-path="0.0.1.0.0.0.1.0">
                            <div class="p-2" data-path="0.0.1.0.0.0.1.0">
                                <div class="bg-black bg-opacity-75 p-4 w-100 rounded-3" data-path="0.0.1.0.0.0.1.0.0">
                                    <span class="d-inline-blockfs-20 fw-medium text-secondary-light text-white mb-0" style="letter-spacing: 1px;" data-config-id="'auto-txt-1-1" data-path="0.0.1.0.0.0.1.0.0.0">건강 보조제 추천</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-12 col-md-6 col-lg-3" data-path="0.0.1.1">
                <a href="#" data-path="0.0.1.1.0">
                    <div class="position-relative mw-100" data-path="0.0.1.1.0.0">
                        <img class="w-100 rounded-3" src="/static/pills_cup.jpg" alt data-config-id="auto-img-2-1" data-path="0.0.1.1.0.0.0">
                        <div class="position-absolute bottom-0 start-0 w-100 rounded-3" data-path="0.0.1.1.0.0.1">
                            <div class="p-2" data-path="0.0.1.1.0.0.1.0">
                                <div class="bg-black bg-opacity-75 p-4 w-100 rounded-3" data-path="0.0.1.1.0.0.1.0.0">
                                    <span class="d-inline-blockfs-20 fw-medium text-secondary-light text-white mb-0" style="letter-spacing: 1px;" data-config-id="'auto-txt-2-1" data-path="0.0.1.0.0.0.1.0.0.0">오늘의 약 성분</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-12 col-md-6 col-lg-3" data-path="0.0.1.2">
                <a href="{{ url_for('question._list') }}" data-path="0.0.1.2.0">
                    <div class="position-relative mw-100" data-path="0.0.1.2.0.0">
                        <img class="rounded-3" src="/static/images.jpg" alt data-config-id="auto-img-3-1" data-path="0.0.1.2.0.0.0">
                        <div class="position-absolute bottom-0 start-0 w-100 rounded-3" data-path="0.0.1.2.0.0.1">
                            <div class="p-2" data-path="0.0.1.2.0.0.1.0">
                                <div class="bg-black bg-opacity-75 p-4 w-100 rounded-3" data-path="0.0.1.2.0.0.1.0.0">
                                    <span class="d-inline-blockfs-20 fw-medium text-secondary-light text-white mb-0" style="letter-spacing: 1px;" data-config-id="'auto-txt-3-1" data-path="0.0.1.2.0.0.1.0.0.0">Q&A 게시판</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </main>
</html>

{% endblock %}